language: node_js
node_js:
  - "6"
install:
  - npm install -g rollup rollup-plugin-buble unicode-9.0.0 && npm i
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  only:
    - master
